version: '3.8'

services:
  # --- USER SERVICE INFRASTRUCTURE ---
  user-db: 
    image: postgres:15-alpine
    container_name: user-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432" 
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user_service # CRITICAL: Point to the sub-folder
    container_name: user-service-app
    env_file:
      - .env # Pulls from the root 
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - user-db
    restart: on-failure

volumes:
  user_postgres_data: # Renamed to keep data separate from Task Service