version: '3.8'

services:
  # --- USER SERVICE ---
  db: 
    image: postgres:15-alpine
    container_name: user-serviceDb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  user-service:
    build: ./user_service
    container_name: user-service-app
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db
    restart: on-failure
    networks:
      - microservice-network

  # --- TASK SERVICE ---
  task-db:
    image: postgres:15-alpine
    container_name: task-serviceDb
    environment:
      - POSTGRES_USER=${TASK_DB_USER}
      - POSTGRES_PASSWORD=${TASK_DB_PASSWORD}
      - POSTGRES_DB=${TASK_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - task_postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network

  task-service:
    build: ./task_service
    container_name: task-service-app
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - task-db
      - user-service
      - notification-service
    restart: on-failure
    networks:
      - microservice-network

  # --- NOTIFICATION SERVICE ---
  notification-db:
    image: postgres:15-alpine
    container_name: notification-serviceDb
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${NOTIFICATION_DB_USER}
      - POSTGRES_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - POSTGRES_DB=${NOTIFICATION_DB_NAME}
    networks:
      - microservice-network
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data

  notification-service:
    build: ./notification_service
    container_name: notification-service-app
    env_file:
      - .env
    ports:
      - "8082:8082"
      - "50052:50052"
    depends_on:
      - notification-db
      - kafka
    restart: on-failure
    networks:
      - microservice-network
  
  # --REPORTING SERVICE ---
  reporting-service:
   build: ./reporting_service
   container_name: reporting-service-app
   env_file:
    - .env
   ports:
    - "8083:8083" 
   depends_on:
      - reporting-db
      - kafka
   restart: on-failure
   networks:
      - microservice-network
  
  reporting-db:
    image: postgres:latest
    container_name: reporting-db
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=${REPORTING_DB_USER}
      - POSTGRES_PASSWORD=${REPORTING_DB_PASSWORD}
      - POSTGRES_DB=${REPORTING_DB_NAME}
    networks:
      - microservice-network
    volumes:
      - reporting_postgres_data:/var/lib/postgresql

  # --- KAFKA INFRASTRUCTURE ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservice-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  user_postgres_data:
  task_postgres_data:
  notification_postgres_data:
  reporting_postgres_data: